apiVersion: apps/v1
kind: Deployment
metadata:
  name: laravel-deployment
  labels:
    app: laravel-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: laravel-app
  template:
    metadata:
      labels:
        app: laravel-app
    spec:
      containers:
        - name: app
          image: korbdaven/laravel-app:latest # 📝 Replace with your built Laravel image
          ports:
            - containerPort: 9000
          env:
            - name: DB_HOST
              value: mysql-service
            - name: DB_PORT
              value: "3306"
            - name: DB_DATABASE
              value: korbdaven-db
            - name: DB_USERNAME
              value: root
            - name: DB_PASSWORD
              value: Hello@123
          volumeMounts:
            - name: laravel-code
              mountPath: /var/www/html

        - name: web
          image: nginx:alpine
          ports:
            - containerPort: 80
          volumeMounts:
            - name: laravel-code
              mountPath: /var/www/html
            - name: nginx-config
              mountPath: /etc/nginx/conf.d

      volumes:
        - name: laravel-code
          emptyDir: {} # replace with PersistentVolumeClaim for real usage
        - name: nginx-config
          configMap:
            name: nginx-config

---
apiVersion: v1
kind: Service
metadata:
  name: laravel-service
spec:
  type: NodePort
  selector:
    app: laravel-app
  ports:
    - name: http
      port: 8087
      targetPort: 80
      nodePort: 30087 # Optional: specific NodePort
